before:
  hooks:
    - go mod download
builds:
  - id: release
    env:
      - CGO_ENABLED=0
      - GO111MODULE=on
    main: ./main.go
    binary: charts-syncer
    ldflags:
      - -X github.com/bitnami/charts-syncer/cmd.version={{.Version}}
dockers:
  -
    ids:
      - release
    dockerfile: Dockerfile
    image_templates:
      - "gcr.io/bitnami-labs/charts-syncer:{{ .Tag }}"
      - "gcr.io/bitnami-labs/charts-syncer:latest"
    build_flag_templates:
      - "--build-arg"
      - "IMAGE_VERSION={{ .Tag }}"
archives:
  - format: tar.gz
    name_template: >-
      {{- .Binary }}_
      {{- .Version }}_
      {{- .Os }}_
      {{- if eq .Arch "amd64" }}x86_64
      {{- else if eq .Arch "386" }}i386
      {{- else }}{{ .Arch }}{{ end }}
      {{- if .Arm }}v{{ .Arm }}{{ end -}}
    format_overrides:
      - goos: windows
        format: zip
    files:
      - README.md
checksum:
  name_template: "checksums.txt"
snapshot:
  name_template: "{{ .Tag }}"
changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"
