before:
  hooks:
    - go mod download
builds:
  - id: release
    env:
      - CGO_ENABLED=0
      - GO111MODULE=on
    main: ./main.go
    binary: charts-syncer
    ldflags:
      - -X github.com/bitnami-labs/charts-syncer/cmd.version={{.Version}}
dockers:
  -
    ids:
      - release
    dockerfile: Dockerfile
    image_templates:
      - "gcr.io/bitnami-labs/charts-syncer:{{ .Tag }}"
      - "gcr.io/bitnami-labs/charts-syncer:latest"
    build_flag_templates:
      - "--build-arg"
      - "IMAGE_VERSION={{ .Tag }}"
archives:
  - replacements:
      386: i386
      amd64: x86_64
    name_template: "{{ .Binary }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}{{ if .Arm }}v{{ .Arm }}{{ end }}{{ if .Mips }}_{{ .Mips }}{{ end }}"
    files:
      - README.md
checksum:
  name_template: "checksums.txt"
snapshot:
  name_template: "{{ .Tag }}"
changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"
