before:
  hooks:
    - go mod download
builds:
  - id: release
    env:
      - CGO_ENABLED=0
      - GO111MODULE=on
    main: ./main.go
    goos:
      - linux
    goarch:
      - arm64
      - amd64
    binary: charts-syncer
    ldflags:
      - -X github.com/bitnami-labs/charts-syncer/cmd.version={{.Version}}
dockers:
  - use: buildx
    ids:
      - release
    goos: linux
    goarch: amd64
    dockerfile: Dockerfile
    image_templates:
      - "release.daocloud.io/charts-syncer/charts-syncer:{{ .Tag }}-amd64"
    build_flag_templates:
      - "--build-arg"
      - "IMAGE_VERSION={{ .Tag }}"
  - use: buildx
    ids:
       - release
    goos: linux
    goarch: arm64
    dockerfile: Dockerfile
    image_templates:
      - "release.daocloud.io/charts-syncer/charts-syncer:{{ .Tag }}-arm64"
    build_flag_templates:
      - "--build-arg"
      - "IMAGE_VERSION={{ .Tag }}"
docker_manifests:
  - name_template: release.daocloud.io/charts-syncer/charts-syncer:{{ .Tag }}
    image_templates:
      - release.daocloud.io/charts-syncer/charts-syncer:{{ .Tag }}-amd64
      - release.daocloud.io/charts-syncer/charts-syncer:{{ .Tag }}-arm64
archives:
  - replacements:
      386: i386
      amd64: x86_64
    name_template: "{{ .Binary }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}{{ if .Arm }}v{{ .Arm }}{{ end }}{{ if .Mips }}_{{ .Mips }}{{ end }}"
    files:
      - README.md
checksum:
  name_template: "checksums.txt"
snapshot:
  name_template: "{{ .Tag }}"
changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"
