run:
  timeout: 10m

linters:
  enable:
    - deadcode
    - dupl
    - gofmt
    - goheader
    - goimports
    # golint replacement
    - gosimple
    - govet
    - ineffassign
    - misspell
    - nakedret
    - revive
    - staticcheck
    - structcheck
    - unused
    - varcheck

linters-settings:
  gofmt:
    simplify: true
  dupl:
    threshold: 400
  goheader:
    template-path: code-header-template.txt
    values:
      regexp:
        copyright-year: 202[1-2]
