// Code generated by protoc-gen-go. DO NOT EDIT.
// source: index.proto

package api

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// ChartMetadata contains relevant information about the released chart
type ChartMetadata struct {
	Version              string   `protobuf:"bytes,1,opt,name=version,proto3" json:"version,omitempty"`
	AppVersion           string   `protobuf:"bytes,2,opt,name=appVersion,proto3" json:"appVersion,omitempty"`
	Name                 string   `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	Urls                 []string `protobuf:"bytes,4,rep,name=urls,proto3" json:"urls,omitempty"`
	Digest               string   `protobuf:"bytes,5,opt,name=digest,proto3" json:"digest,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ChartMetadata) Reset()         { *m = ChartMetadata{} }
func (m *ChartMetadata) String() string { return proto.CompactTextString(m) }
func (*ChartMetadata) ProtoMessage()    {}
func (*ChartMetadata) Descriptor() ([]byte, []int) {
	return fileDescriptor_f750e0f7889345b5, []int{0}
}

func (m *ChartMetadata) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ChartMetadata.Unmarshal(m, b)
}
func (m *ChartMetadata) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ChartMetadata.Marshal(b, m, deterministic)
}
func (m *ChartMetadata) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ChartMetadata.Merge(m, src)
}
func (m *ChartMetadata) XXX_Size() int {
	return xxx_messageInfo_ChartMetadata.Size(m)
}
func (m *ChartMetadata) XXX_DiscardUnknown() {
	xxx_messageInfo_ChartMetadata.DiscardUnknown(m)
}

var xxx_messageInfo_ChartMetadata proto.InternalMessageInfo

func (m *ChartMetadata) GetVersion() string {
	if m != nil {
		return m.Version
	}
	return ""
}

func (m *ChartMetadata) GetAppVersion() string {
	if m != nil {
		return m.AppVersion
	}
	return ""
}

func (m *ChartMetadata) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *ChartMetadata) GetUrls() []string {
	if m != nil {
		return m.Urls
	}
	return nil
}

func (m *ChartMetadata) GetDigest() string {
	if m != nil {
		return m.Digest
	}
	return ""
}

// Index describes a chart releases index
type Index struct {
	Entries              map[string]*Index_ChartEntries `protobuf:"bytes,1,rep,name=entries,proto3" json:"entries,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	ApiVersion           string                         `protobuf:"bytes,2,opt,name=api_version,json=apiVersion,proto3" json:"api_version,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                       `json:"-"`
	XXX_unrecognized     []byte                         `json:"-"`
	XXX_sizecache        int32                          `json:"-"`
}

func (m *Index) Reset()         { *m = Index{} }
func (m *Index) String() string { return proto.CompactTextString(m) }
func (*Index) ProtoMessage()    {}
func (*Index) Descriptor() ([]byte, []int) {
	return fileDescriptor_f750e0f7889345b5, []int{1}
}

func (m *Index) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Index.Unmarshal(m, b)
}
func (m *Index) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Index.Marshal(b, m, deterministic)
}
func (m *Index) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Index.Merge(m, src)
}
func (m *Index) XXX_Size() int {
	return xxx_messageInfo_Index.Size(m)
}
func (m *Index) XXX_DiscardUnknown() {
	xxx_messageInfo_Index.DiscardUnknown(m)
}

var xxx_messageInfo_Index proto.InternalMessageInfo

func (m *Index) GetEntries() map[string]*Index_ChartEntries {
	if m != nil {
		return m.Entries
	}
	return nil
}

func (m *Index) GetApiVersion() string {
	if m != nil {
		return m.ApiVersion
	}
	return ""
}

type Index_ChartEntries struct {
	Versions             []*ChartMetadata `protobuf:"bytes,1,rep,name=versions,proto3" json:"versions,omitempty"`
	XXX_NoUnkeyedLiteral struct{}         `json:"-"`
	XXX_unrecognized     []byte           `json:"-"`
	XXX_sizecache        int32            `json:"-"`
}

func (m *Index_ChartEntries) Reset()         { *m = Index_ChartEntries{} }
func (m *Index_ChartEntries) String() string { return proto.CompactTextString(m) }
func (*Index_ChartEntries) ProtoMessage()    {}
func (*Index_ChartEntries) Descriptor() ([]byte, []int) {
	return fileDescriptor_f750e0f7889345b5, []int{1, 0}
}

func (m *Index_ChartEntries) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Index_ChartEntries.Unmarshal(m, b)
}
func (m *Index_ChartEntries) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Index_ChartEntries.Marshal(b, m, deterministic)
}
func (m *Index_ChartEntries) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Index_ChartEntries.Merge(m, src)
}
func (m *Index_ChartEntries) XXX_Size() int {
	return xxx_messageInfo_Index_ChartEntries.Size(m)
}
func (m *Index_ChartEntries) XXX_DiscardUnknown() {
	xxx_messageInfo_Index_ChartEntries.DiscardUnknown(m)
}

var xxx_messageInfo_Index_ChartEntries proto.InternalMessageInfo

func (m *Index_ChartEntries) GetVersions() []*ChartMetadata {
	if m != nil {
		return m.Versions
	}
	return nil
}

func init() {
	proto.RegisterType((*ChartMetadata)(nil), "api.ChartMetadata")
	proto.RegisterType((*Index)(nil), "api.Index")
	proto.RegisterMapType((map[string]*Index_ChartEntries)(nil), "api.Index.EntriesEntry")
	proto.RegisterType((*Index_ChartEntries)(nil), "api.Index.ChartEntries")
}

func init() {
	proto.RegisterFile("index.proto", fileDescriptor_f750e0f7889345b5)
}

var fileDescriptor_f750e0f7889345b5 = []byte{
	// 312 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x5c, 0x51, 0x3f, 0x4b, 0x3b, 0x41,
	0x10, 0xe5, 0x72, 0xf9, 0xf3, 0xfb, 0x4d, 0x22, 0xc8, 0x14, 0x7a, 0xa4, 0xd0, 0x90, 0x2a, 0x4d,
	0xee, 0x50, 0x1b, 0x51, 0x08, 0xa2, 0x58, 0x58, 0xd8, 0x9c, 0x60, 0x61, 0x23, 0x73, 0xc9, 0x90,
	0x0c, 0x5e, 0xf6, 0x96, 0xdd, 0x4d, 0x30, 0x1f, 0xc1, 0x6f, 0xeb, 0x47, 0x90, 0xdd, 0x5c, 0x24,
	0xb1, 0xda, 0x99, 0xf7, 0xde, 0xf0, 0xde, 0xce, 0x40, 0x57, 0xd4, 0x8c, 0x3f, 0x53, 0x6d, 0x2a,
	0x57, 0x61, 0x4c, 0x5a, 0x86, 0x5f, 0x11, 0x1c, 0x3d, 0x2c, 0xc8, 0xb8, 0x67, 0x76, 0x34, 0x23,
	0x47, 0x98, 0x40, 0x67, 0xcd, 0xc6, 0x4a, 0xa5, 0x92, 0x68, 0x10, 0x8d, 0xfe, 0xe7, 0xbb, 0x16,
	0xcf, 0x00, 0x48, 0xeb, 0xd7, 0x9a, 0x6c, 0x04, 0x72, 0x0f, 0x41, 0x84, 0xa6, 0xa2, 0x25, 0x27,
	0x71, 0x60, 0x42, 0xed, 0xb1, 0x95, 0x29, 0x6d, 0xd2, 0x1c, 0xc4, 0x1e, 0xf3, 0x35, 0x9e, 0x40,
	0x7b, 0x26, 0x73, 0xb6, 0x2e, 0x69, 0x05, 0x65, 0xdd, 0x0d, 0xbf, 0x23, 0x68, 0x3d, 0xf9, 0x80,
	0x78, 0x01, 0x1d, 0x56, 0xce, 0x08, 0xdb, 0x24, 0x1a, 0xc4, 0xa3, 0xee, 0xe5, 0x69, 0x4a, 0x5a,
	0xd2, 0x40, 0xa6, 0x8f, 0x5b, 0xc6, 0x3f, 0x9b, 0x7c, 0xa7, 0xc3, 0x73, 0xe8, 0x92, 0x96, 0xf7,
	0xf5, 0xdf, 0x74, 0x52, 0xa7, 0xeb, 0x4f, 0xa0, 0x17, 0x3e, 0x5a, 0x8f, 0x63, 0x0a, 0xff, 0x6a,
	0xf1, 0xce, 0x04, 0x83, 0xc9, 0xc1, 0x36, 0xf2, 0x5f, 0x4d, 0xff, 0x05, 0x7a, 0xfb, 0xce, 0x78,
	0x0c, 0xf1, 0x07, 0x6f, 0xea, 0x1d, 0xf9, 0x12, 0xc7, 0xd0, 0x5a, 0x53, 0xb9, 0xe2, 0x60, 0x7e,
	0x98, 0x79, 0xdf, 0x39, 0xdf, 0xaa, 0x6e, 0x1a, 0xd7, 0xd1, 0xfd, 0xdd, 0xdb, 0x64, 0x2e, 0x6e,
	0xb1, 0x2a, 0xd2, 0x69, 0xb5, 0xcc, 0x0a, 0x71, 0x8a, 0x96, 0x32, 0x2e, 0xa9, 0xb0, 0xd9, 0xd4,
	0x8f, 0xd8, 0xb1, 0xdd, 0xa8, 0x29, 0x9b, 0x4c, 0x94, 0x63, 0xa3, 0xa8, 0xcc, 0xc2, 0x05, 0xd9,
	0x64, 0xa4, 0xe5, 0x96, 0xb4, 0x14, 0xed, 0x70, 0xcc, 0xab, 0x9f, 0x00, 0x00, 0x00, 0xff, 0xff,
	0x9f, 0x3d, 0x8b, 0x53, 0xdb, 0x01, 0x00, 0x00,
}
