apiVersion: batch/v1
kind: CronJob
metadata:
  name: charts-syncer
spec:
  schedule: "*/30 * * * *"
  # If a job is scheduled wait for it to finish
  concurrencyPolicy: Forbid
  jobTemplate:
    spec:
      template:
        spec:
          securityContext:
            fsGroup: 1001
            fsGroupChangePolicy: OnRootMismatch
            supplementalGroups: []
            sysctls: []
          containers:
          - name: charts-syncer
            imagePullPolicy: Always
            image: bitnami/charts-syncer:2.1.1
            args: ["sync", "--config", "/charts-syncer.yaml", "-v", "4", "--latest-version-only"]
            env:
              # Helm Chart source repository credentials
              - name: SOURCE_REPO_AUTH_USERNAME
                valueFrom:
                  secretKeyRef:
                    name: charts-syncer-credentials
                    key: SOURCE_REPO_AUTH_USERNAME
              - name: SOURCE_REPO_AUTH_PASSWORD
                valueFrom:
                  secretKeyRef:
                    name: charts-syncer-credentials
                    key: SOURCE_REPO_AUTH_PASSWORD
              # Helm Chart target repository credentials
              - name: TARGET_REPO_AUTH_USERNAME
                valueFrom:
                  secretKeyRef:
                    name: charts-syncer-credentials
                    key: TARGET_REPO_AUTH_USERNAME
              - name: TARGET_REPO_AUTH_PASSWORD
                valueFrom:
                  secretKeyRef:
                    name: charts-syncer-credentials
                    key: TARGET_REPO_AUTH_PASSWORD
              # Container images source registry credentials
              - name: SOURCE_CONTAINERS_AUTH_REGISTRY
                valueFrom:
                  secretKeyRef:
                    name: charts-syncer-credentials
                    key: SOURCE_CONTAINERS_AUTH_REGISTRY
              - name: SOURCE_CONTAINERS_AUTH_USERNAME
                valueFrom:
                  secretKeyRef:
                    name: charts-syncer-credentials
                    key: SOURCE_CONTAINERS_AUTH_USERNAME
              - name: SOURCE_CONTAINERS_AUTH_PASSWORD
                valueFrom:
                  secretKeyRef:
                    name: charts-syncer-credentials
                    key: SOURCE_CONTAINERS_AUTH_PASSWORD
              # Container images target registry credentials
              - name: TARGET_CONTAINERS_AUTH_USERNAME
                valueFrom:
                  secretKeyRef:
                    name: charts-syncer-credentials
                    key: TARGET_CONTAINERS_AUTH_USERNAME
              - name: TARGET_CONTAINERS_AUTH_PASSWORD
                valueFrom:
                  secretKeyRef:
                    name: charts-syncer-credentials
                    key: TARGET_CONTAINERS_AUTH_PASSWORD
              - name: TARGET_CONTAINERS_AUTH_REGISTRY
                valueFrom:
                  secretKeyRef:
                    name: charts-syncer-credentials
                    key: TARGET_CONTAINERS_AUTH_REGISTRY
            securityContext:
              runAsUser: 1001
              runAsGroup: 1001
              allowPrivilegeEscalation: false
              capabilities:
                drop:
                - ALL
              privileged: false
              readOnlyRootFilesystem: true
              runAsNonRoot: true
              seLinuxOptions: {}
              seccompProfile:
                type: RuntimeDefault
            volumeMounts:
              - name: config
                mountPath: /charts-syncer.yaml
                subPath: charts-syncer.yaml
              - name: empty-dir
                mountPath: /tmp
              - name: empty-dir
                mountPath: /.charts-syncer
          restartPolicy: OnFailure
          volumes:
            - name: empty-dir
              emptyDir: {}
            - name: config
              configMap:
                name: charts-syncer-config
