#
# Example config file to sync a well-known chart repo to a local directory
#

# We are not syncing all charts, for simplicity
charts:
- etcd
- harbor
- nginx
- redis

# The bitnami chart repo is a well-known chart repository that we can use
# as source.
source:
  repo:
    kind: HELM
    url: https://charts.bitnami.com/bitnami

target:
  # The bitnami charts use docker as default container registry. Let's switch
  # to one of their mirrors to ensure the container references reallocation works.
  #
  # NOTE: This does not reallocate container artifacts, actually, but their
  #       references in the chart.
  containerRegistry: docker.io
  containerRepository: bitnami
  repo:
    kind: LOCAL
    path: ./local-repo

