#
# Example config file to sync a well-known chart repo to a local directory
#

# We are not syncing all charts, for simplicity
charts:
- etcd
- harbor
- nginx
- redis

# The bitnami chart repo is a well-known chart repository that we can use
# as source.
source:
  repo:
    kind: HELM
    url: https://charts.bitnami.com/bitnami

target:
  repo:
    kind: LOCAL
    path: ./local-repo

