name: CI
on:
  workflow_dispatch:
  push: 
    branches:
       - v2
  pull_request:
    branches:
      - v2
    types:
      - assigned 
      - opened 
      - synchronize 
      - reopened

env:
  KIND_VERSION: "0.12.0"
  KUBECTL_VERSION: "1.22.0"

jobs:
  Validate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@1af3b93b6815bc44a9784bd300feb67ff0d1eeb3 # v3
        with:
          fetch-depth: 0
      - name: Set Golang
        uses: actions/setup-go@v6
        with:
          go-version: '^1.25'

      - name: Set Golangci-lint
        run: curl -sSfL https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh | sh -s -- -b $(go env GOPATH)/bin v2.4.0

      - name: Set Shellcheck
        run: sudo apt-get -qq update && sudo apt-get install -y shellcheck

      - name: Verify scripts
        run: |
           shellcheck test/*.sh

      - name: Build
        run: make build
      - name: Lint
        run: make test-style

      - name: Test
        run: make test

  Build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@1af3b93b6815bc44a9784bd300feb67ff0d1eeb3 # v3
        with:
          fetch-depth: 0
      - name: Set Golang
        uses: actions/setup-go@v6
        with:
          go-version: '^1.25'

      - name: Build
        run: make build
      - uses: actions/upload-artifact@v6.0.0
        with:
          name: charts-syncer-binary
          path: dist/charts-syncer

  Integration:
    needs: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@1af3b93b6815bc44a9784bd300feb67ff0d1eeb3 # v3
        with:
          fetch-depth: 0
      - name: Get Registry Local IP
        run: |
          echo "REGISTRY_IP=$(hostname -I | cut -d" " -f1)" >> $GITHUB_ENV
      - uses: actions/download-artifact@v6
        with:
            name: charts-syncer-binary
            path: /tmp/dist
      - name: Install Kind
        run: |
           curl -LO https://github.com/kubernetes-sigs/kind/releases/download/v${KIND_VERSION}/kind-Linux-amd64
           chmod +x kind-Linux-amd64
           sudo mv kind-Linux-amd64 /usr/local/bin/kind
      - name: Create kind cluster
        run: |
           ./test/kind-create-cluster.sh
           echo "KUBECONFIG=$HOME/.kube/config" >> $GITHUB_ENV
      - name: Set Helm
        uses: azure/setup-helm@1a275c3b69536ee54be43f2070a358922e12c8d4 # v4.3.1
        with:
          version: v3.12.1
      - name: Run OCI Source Registry
        run: |
          docker run --name local-source-registry -p 5001:5000 -d registry:2
      - name: Push local wordpress and mariadb charts
        run: |
          helm push test/wordpress-27.0.7.tgz oci://127.0.0.1:5001/library
          helm push test/mariadb-23.0.4.tgz oci://127.0.0.1:5001/library
      - name: Run OCI Target Registry
        run: |
           docker run --name local-target-registry -p 5000:5000 -d registry:2
      - name: Install Kubectl
        run: |
           curl -LO https://storage.googleapis.com/kubernetes-release/release/v${KUBECTL_VERSION}/bin/linux/amd64/kubectl
           chmod +x kubectl
           sudo mv kubectl /usr/local/bin
      - name: Install wait-for-port
        run: |
           curl -LO https://github.com/bitnami/wait-for-port/releases/download/v1.0/wait-for-port.zip
           unzip wait-for-port.zip
           chmod +x wait-for-port
           sudo mv wait-for-port /usr/local/bin/
      - name: Run charts-syncer
        run: |
           chmod +x /tmp/dist/charts-syncer
           ./test/run-charts-syncer.sh
      - run: ./test/install-wordpress.sh
      - run: ./test/wait-for-wordpress-deployment.sh
      - run: ./test/run-verifications.sh
