name: Release

on:
  push:
    tags:
      - "v*.*.*"

jobs:
  release:
    runs-on: ubuntu-latest
    env:
      dockerhub_image_name: docker.io/bitnami/charts-syncer
      ghcr_image_name: ghcr.io/bitnami/charts-syncer
    steps:
      - name: Checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
      - name: Unshallow
        run: git fetch --prune --unshallow
      # Obtain the release version from the tag without the 'v' prefix
      - name: Write release version
        run: |
          VERSION_TAG=${GITHUB_REF_NAME#v}
          echo Version: $VERSION_TAG
          echo "VERSION_TAG=$VERSION_TAG" >> $GITHUB_ENV
      - name: Set up Go
        uses: actions/setup-go@4b73464bb391d4059bd26b0524d20df3927bd417 # v6.3.0
        with:
          go-version: '^1.26'
      # Setup env for multi-arch builds
      - name: Set up QEMU
        uses: docker/setup-qemu-action@ce360397dd3f832beb865e1373c09c0e9f86d70a # v4.0.0
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@4d04d5d9486b7bd6fa91e7baf45bbb4f8b9deedd # v4.0.0
      # Build binaries
      - name: Release
        uses: goreleaser/goreleaser-action@ec59f474b9834571250b370d4735c50f8e2d1e29 # v7.0.0
        with:
          version: latest
          args: release --clean
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      # Build & Publish multi-arch image
      - name: Login to Docker Hub
        uses: docker/login-action@4907a6ddec9925e35a0a9e82d7399ccc52663121 # v4.1.0
        with:
          username: ${{ secrets.BITNAMI_USERNAME }}
          password: ${{ secrets.BITNAMI_PASSWORD }}
      - name: Login to GHRC
        uses: docker/login-action@4907a6ddec9925e35a0a9e82d7399ccc52663121 # v4.1.0
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Extract image metadata (tags, labels)
        id: metadata
        uses: docker/metadata-action@030e881283bb7a6894de51c315a6bfe6a94e05cf # v6.0.0
        with:
          images: |
            ${{ env.dockerhub_image_name }}
            ${{ env.ghcr_image_name }}
          # Image tags: 'latest', '2' and the tagged version without the 'v' prefix
          tags: |
            type=raw,value=2
            type=raw,value=${{ env.VERSION_TAG }}
            type=raw,value=latest
      - name: Build and push image
        id: docker_build
        uses: docker/build-push-action@d08e5c354a6adb9ed34480a06d141179aa583294 # v7.0.0
        env:
          # Disable attestation to prevent 'unknown/unknown' artifacts in GHCR
          BUILDX_NO_DEFAULT_ATTESTATIONS: 1
        with:
          context: .
          file: ./Dockerfile
          platforms: linux/amd64,linux/arm64
          push: true
          tags: ${{ steps.metadata.outputs.tags }}
          labels: ${{ steps.metadata.outputs.labels }}
