name: Release

on:
  push:
    tags:
      - "v*.*.*"

jobs:
  release:
    runs-on: ubuntu-latest
    env:
      dockerhub_image_name: docker.io/bitnami/charts-syncer
      ghcr_image_name: ghcr.io/bitnami/charts-syncer
    steps:
      - name: Checkout
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
      - name: Unshallow
        run: git fetch --prune --unshallow
      # Obtain the release version from the tag without the 'v' prefix
      - name: Write release version
        run: |
          VERSION_TAG=${GITHUB_REF_NAME#v}
          echo Version: $VERSION_TAG
          echo "VERSION_TAG=$VERSION_TAG" >> $GITHUB_ENV
      - name: Set up Go
        uses: actions/setup-go@924ae3a1cded613372ab5595356fb5720e22ba16 # v6.5.0
        with:
          go-version: '^1.26'
      # Setup env for multi-arch builds
      - name: Set up QEMU
        uses: docker/setup-qemu-action@06116385d9baf250c9f4dcb4858b16962ea869c3 # v4.1.0
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@d7f5e7f509e45cec5c76c4d5afdd7de93d0b3df5 # v4.1.0
      # Build binaries
      - name: Release
        uses: goreleaser/goreleaser-action@5daf1e915a5f0af01ddbcd89a43b8061ff4f1a89 # v7.2.2
        with:
          version: latest
          args: release --clean
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      # Build & Publish multi-arch image
      - name: Login to Docker Hub
        uses: docker/login-action@650006c6eb7dba73a995cc03b0b2d7f5ca915bee # v4.2.0
        with:
          username: ${{ secrets.BITNAMI_USERNAME }}
          password: ${{ secrets.BITNAMI_PASSWORD }}
      - name: Login to GHRC
        uses: docker/login-action@650006c6eb7dba73a995cc03b0b2d7f5ca915bee # v4.2.0
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Extract image metadata (tags, labels)
        id: metadata
        uses: docker/metadata-action@80c7e94dd9b9319bd5eb7a0e0fe9291e23a2a2e9 # v6.1.0
        with:
          images: |
            ${{ env.dockerhub_image_name }}
            ${{ env.ghcr_image_name }}
          # Image tags: 'latest', '2' and the tagged version without the 'v' prefix
          tags: |
            type=raw,value=2
            type=raw,value=${{ env.VERSION_TAG }}
            type=raw,value=latest
      - name: Build and push image
        id: docker_build
        uses: docker/build-push-action@f9f3042f7e2789586610d6e8b85c8f03e5195baf # v7.2.0
        env:
          # Disable attestation to prevent 'unknown/unknown' artifacts in GHCR
          BUILDX_NO_DEFAULT_ATTESTATIONS: 1
        with:
          context: .
          file: ./Dockerfile
          platforms: linux/amd64,linux/arm64
          push: true
          tags: ${{ steps.metadata.outputs.tags }}
          labels: ${{ steps.metadata.outputs.labels }}
